### ISSUE TITLE
Checklist to confirm PHP 8.2 compatibility

### ISSUE THREAD

**Issue by IMSoP** [Shardj/zf1-future#449]
Since [PHP has a policy of avoid Breaking Changes in "minor" releases](https://wiki.php.net/rfc/releaseprocess), the library should in theory be compatible with any PHP 8.x. In practice, each PHP release has a small number of breaking changes, which might require small adjustments. (Note that there will be a larger list of new Warnings and Deprecations, but fixing these is not essential to consider the library compatible.)

For PHP 8.2, [the manual lists the following incompatible changes](https://www.php.net/manual/en/migration82.incompatible.php). Once we have checked all of them, it should be safe to consider the library "PHP 8.2 compatible".

- [x] [DateTime::createFromImmutable()](https://www.php.net/manual/en/datetime.createfromimmutable.php) now has a tentative return type of static, previously it was [DateTime](https://www.php.net/manual/en/class.datetime.php).
  * "Tentative return types" are a concept only introduced in PHP 8.1 (as a step towards a PHP 9.0 or later change); so this library won't care about them at all
- [x] [DateTimeImmutable::createFromMutable()](https://www.php.net/manual/en/datetimeimmutable.createfrommutable.php) now has a tentative return type of static, previously it was [DateTimeImmutable](https://www.php.net/manual/en/class.datetimeimmutable.php).
  * As above
- [x] number symbols in [relative date formats](https://www.php.net/manual/en/datetime.formats.php#datetime.formats.relative) no longer accept multiple signs, e.g. +-2.
  * Searching for "-+" and "+-" shows no relevant code. Seems very unlikely to be a problem.
- [x] ODBC and PDO_ODBC
  * as far as I can see, the library doesn't directly support either of these extensions
- [x] [glob()](https://www.php.net/manual/en/function.glob.php) now returns an empty [array](https://www.php.net/manual/en/language.types.array.php) if all paths are restricted by [open_basedir](https://www.php.net/manual/en/ini.core.php#ini.open-basedir). Previously it returned [false](https://www.php.net/manual/en/reserved.constants.php#constant.false).
  * 9 uses of `glob()`; most already assume the result is an array
  * `\Zend_Cache_Backend_File::_clean` does explicitly check for `false`, but only to shortcut the function and avoid a `foreach` loop
- [x] [FilesystemIterator::__construct()](https://www.php.net/manual/en/filesystemiterator.construct.php): prior to PHP 8.2.0, [FilesystemIterator::SKIP_DOTS](https://www.php.net/manual/en/class.filesystemiterator.php#filesystemiterator.constants.skip-dots) constant was always set and couldn't be disabled.
  * No uses.
- [x] [strtolower()](https://www.php.net/manual/en/function.strtolower.php), [strtoupper()](https://www.php.net/manual/en/function.strtoupper.php), [stristr()](https://www.php.net/manual/en/function.stristr.php), [stripos()](https://www.php.net/manual/en/function.stripos.php), [strripos()](https://www.php.net/manual/en/function.strripos.php), [lcfirst()](https://www.php.net/manual/en/function.lcfirst.php), [ucfirst()](https://www.php.net/manual/en/function.ucfirst.php), [ucwords()](https://www.php.net/manual/en/function.ucwords.php), and [str_ireplace()](https://www.php.net/manual/en/function.str-ireplace.php) are no longer locale-sensitive.
  * The library never sets the system locale; the only use of `setlocale()` is to fetch the current setting (`setlocale(LC_ALL, 0)`)
- [x] [str_split()](https://www.php.net/manual/en/function.str-split.php) returns an empty [array](https://www.php.net/manual/en/language.types.array.php) for an empty [string](https://www.php.net/manual/en/language.types.string.php) now.
  * There are a bunch of uses of this. There is a slim chance that one of them was accidentally relying on this behaviour.
- [ ] [ksort()](https://www.php.net/manual/en/function.ksort.php) and [krsort()](https://www.php.net/manual/en/function.krsort.php) now do numeric string comparison under [SORT_REGULAR](https://www.php.net/manual/en/array.constants.php#constant.sort-regular) using the standard PHP 8 rules now.
  * This seems to be about comparing mixed lists of strings and numbers.
  * There are a handful of uses of these functions in the library; it's unlikely any are affected, but we could look closely to be sure.
- [ ] [var_export()](https://www.php.net/manual/en/function.var-export.php) no longer omits the leading backslash for exported classes, i.e. these are now fully qualified.
  * Non-debug uses are in `bin/classmap_generator.php`, `library/Zend/CodeGenerator/Php/Parameter.php`, `library/Zend/Serializer/Adapter/PhpCode.php`, and `library/Zend/Config/Writer/Array.php`
  * It's unlikely these will break with the extra backslash, but we could test each to be sure.
- [x] [GlobIterator](https://www.php.net/manual/en/class.globiterator.php) now returns an empty [array](https://www.php.net/manual/en/language.types.array.php) if all paths are restricted by [open_basedir](https://www.php.net/manual/en/ini.core.php#ini.open-basedir).
  * No uses.
- [x] The following methods now enforce their signature: SplFileInfo::_bad_state_ex(); [SplFileObject::getCsvControl()](https://www.php.net/manual/en/splfileobject.getcsvcontrol.php); [SplFileObject::fflush()](https://www.php.net/manual/en/splfileobject.fflush.php); [SplFileObject::ftell()](https://www.php.net/manual/en/splfileobject.ftell.php); [SplFileObject::fgetc()](https://www.php.net/manual/en/splfileobject.fgetc.php); [SplFileObject::fpassthru()](https://www.php.net/manual/en/splfileobject.fpassthru.php)
  * Class is referenced in library/Zend/File/PhpClassFile.php and library/Zend/File/ClassFileLocator.php but no use of the affected methods
- [x] [SplFileObject::hasChildren()](https://www.php.net/manual/en/splfileobject.haschildren.php) now has a tentative return type of [false](https://www.php.net/manual/en/language.types.value.php), previously it was [bool](https://www.php.net/manual/en/language.types.boolean.php). [SplFileObject::getChildren()](https://www.php.net/manual/en/splfileobject.getchildren.php) now has a tentative return type of [null](https://www.php.net/manual/en/language.types.null.php), previously it was ?[RecursiveIterator](https://www.php.net/manual/en/class.recursiveiterator.php).
  * No uses of SplFileObject.

**Comment by IMSoP** [comment]
None of the uses of `var_export` makes any assumption about the exact shape of the output, only that it's valid PHP. If anything, the change will improve them, by outputting code that could be executed correctly in a namespaced context.

None of the uses of `ksort` or `krsort` seem to be making any strong assumptions about the order of data, except in the case of some which are using only numeric keys anyway.

**Comment by ferranbonas** [comment]
All items in the checklist appear to be verified as compatible:
- `var_export`: ✅
- `ksort` / `krsort`: ✅
- `glob()`: Already correctly handles false in `Zend_Cache_Backend_File`
- `setlocale()`: Mostly used for reading current settings, which is acceptable

Can we consider this officially PHP 8.2 compatible?

**Comment by develart-projects** [comment]
I'm about to do some migrations this summer, so I can give feedback afterwards.
Basically we are talking here just about the project description change.

**Comment by sreichel** [comment]
https://github.com/Shardj/zf1-future/actions/runs/14320283287/job/40135623330#step:7:1

Maybe that issue should be reviewed?

**Comment by ouslie** [comment]
Hello,
Do you have any news about PHP 8.2 compatibility? What potential issues should we expect?

**Comment by rruchte** [comment]
I've been running on 8.3 for a while with no issues.

**Comment by develart-projects** [comment]
According to all the discussions, next release will be (soon) 1.25.0, dropping 7.1-7.3 support, adding 8.2.
I have to adjust some stuff in docs and composer, then we are good to go.
