### ISSUE TITLE
Checklist to confirm PHP 8.3 compatibility

### ISSUE THREAD

**Issue by IMSoP** [Shardj/zf1-future#450]
Since [PHP has a policy of avoid Breaking Changes in "minor" releases](https://wiki.php.net/rfc/releaseprocess), the library should in theory be compatible with any PHP 8.x. In practice, each PHP release has a small number of breaking changes, which might require small adjustments. (Note that there will be a larger list of new Warnings and Deprecations, but fixing these is not essential to consider the library compatible.)

For PHP 8.3, [the manual lists the following incompatible changes](https://www.php.net/manual/en/migration83.incompatible.php). Once we have checked all of them, it should be safe to consider the library "PHP 8.3 compatible".

- [x] Programs that were very close to overflowing the call stack may now throw an [Error](https://www.php.net/manual/en/class.error.php) when using more than zend.max_allowed_stack_size-zend.reserved_stack_size bytes of stack
  * Not something a library / framework needs to worry about
- [x] Executing [proc_get_status()](https://www.php.net/manual/en/function.proc-get-status.php) multiple times will now always return the right value on POSIX systems. [...] Executing [proc_close()](https://www.php.net/manual/en/function.proc-close.php) after [proc_get_status()](https://www.php.net/manual/en/function.proc-get-status.php) will now also return the right exit code.
  * No uses.
- [ ] Zend Max Execution Timers is now enabled by default for ZTS builds on Linux. 
- [ ] Uses of traits with static properties will now redeclare static properties inherited from the parent class. This will create a separate static property storage for the current class. This is analogous to adding the static property to the class directly without traits. 
- [ ] Assigning a negative index $n to an empty array will now make sure that the next index is $n+1 instead of 0. 
- [ ] Class constant visibility variance is now correctly checked when inherited from interfaces. 
- [x] [WeakMap](https://www.php.net/manual/en/class.weakmap.php) entries whose key maps to itself (possibly transitively) may now be removed during cycle collection if the key is not reachable except by iterating over the WeakMap (reachability via iteration is considered weak). Previously, such entries would never be automatically removed.
  * No uses
- [ ] The DateTime extension has introduced Date extension specific exceptions and errors under the [DateError](https://www.php.net/manual/en/class.dateerror.php) and [DateException](https://www.php.net/manual/en/class.dateexception.php) hierarchies, instead of warnings and generic exceptions.
- [ ] Calling [DOMChildNode::after()](https://www.php.net/manual/en/domchildnode.after.php), [DOMChildNode::before()](https://www.php.net/manual/en/domchildnode.before.php), [DOMChildNode::replaceWith()](https://www.php.net/manual/en/domchildnode.replacewith.php) on a node that has no parent is now a no-op instead of a hierarchy exception, which is the behaviour demanded by the DOM specification.
- [ ] Using the [DOMParentNode](https://www.php.net/manual/en/class.domparentnode.php) and [DOMChildNode](https://www.php.net/manual/en/class.domchildnode.php) methods without a document now works instead of throwing a [DOM_HIERARCHY_REQUEST_ERR](https://www.php.net/manual/en/dom.constants.php#constant.dom-hierarchy-request-err) [DOMException](https://www.php.net/manual/en/class.domexception.php). This is in line with the behaviour demanded by the DOM specification.
- [ ] Calling [DOMDocument::createAttributeNS()](https://www.php.net/manual/en/domdocument.createattributens.php) without specifying a prefix would incorrectly create a default namespace, placing the element inside the namespace instead of the attribute. This bug is now fixed.
- [ ] [DOMDocument::createAttributeNS()](https://www.php.net/manual/en/domdocument.createattributens.php) would previously incorrectly throw a DOM_NAMESPACE_ERRNAMESPACE_ERR [DOMException](https://www.php.net/manual/en/class.domexception.php) when the prefix was already used for a different URI. It now correctly chooses a different prefix when there's a prefix name conflict.
- [ ] New methods and properties were added to some DOM classes. If a userland class inherits from these classes and declare a method or property with the same name, the declarations must be compatible. Otherwise, a typical compile error about incompatible declarations will be thrown. See the [list of new features](https://www.php.net/manual/en/migration83.new-features.php#migration83.new-features.dom) and [new functions](https://www.php.net/manual/en/migration83.new-functions.php#migration83.new-functions.dom) for a list of the newly implemented methods and properties.
- [x] FFI: C functions that have a return type of [void](https://www.php.net/manual/en/language.types.void.php) now return [null](https://www.php.net/manual/en/reserved.constants.php#constant.null) instead of returning the following object `object(FFI\CData:void) { }`
  * No uses
- [ ] The [opcache.consistency_checks](https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.consistency-checks) INI directive was removed.
- [ ] The type of [Phar](https://www.php.net/manual/en/class.phar.php) class constants are now declared.
- [ ] The [range()](https://www.php.net/manual/en/function.range.php) function has had various changes (see [Changelog](https://www.php.net/manual/en/function.range.php#refsect1-function.range-changelog))
- [ ] [number_format()](https://www.php.net/manual/en/function.number-format.php) now handles negative $decimals values by rounding $num to abs($decimals) digits before the decimal point. Previously, negative $decimals values were ignored.
- [ ] The [file()](https://www.php.net/manual/en/function.file.php) flags error check now catches all invalid flags. Notably [FILE_APPEND](https://www.php.net/manual/en/filesystem.constants.php#constant.file-append) was previously silently accepted.
- [x] The type of [SNMP](https://www.php.net/manual/en/class.snmp.php) class constants are now declared.
  * No uses

**Comment by sirber** [comment]
with ZF 1.21.2 on PHP 8.3.15 :

Deprecated: Creation of dynamic property TimeController::$ajaxable is deprecated in /app/vendor/shardj/zf1-future/library/Zend/Controller/Action/Helper/ContextSwitch.php on line 1148

**Comment by IMSoP** [comment]
@sirber Deprecation notices mark things which **will be incompatible in future versions**. In this case, the message is saying that a change is necessary **to be compatible with PHP 9.0** (which doesn't exist yet, and probably won't until at least November 2026).

***If*** the change is safe (i.e. if the code is not relying on the property being dynamic, and if `protected` is definitely the right access level), then proposing a Pull Request with that change will be helpful. But it is not relevant to this issue, which is a list of things which might be *incompatible with PHP 8.3*, that is they will produce **errors** (not informational notices), or change behaviour.

**Comment by boenrobot** [comment]
> Class constant visibility variance is now correctly checked when inherited from interfaces.

I think this one can also be checked, as no visibility constants are used in this project... Though I guess we may, since that feature was added in PHP 7.1.

**Comment by develart-projects** [comment]
> with ZF 1.24.2 on PHP 8.3.15 :
> 
> Deprecated: Creation of dynamic property TimeController::$ajaxable is deprecated in /app/vendor/shardj/zf1-future/library/Zend/Controller/Action/Helper/ContextSwitch.php on line 1148
> 
> I quick fixed it on my side:
> 
> ![image](https://github.com/user-attachments/assets/53108375-6e30-43dd-aacf-875629fc9e18)

Maybe we can fix this by simply adding public $ajaxable to keep it inlined?

**Comment by sreichel** [comment]
IMHO it has to be public to prevent access to protected property. (?)

**Comment by sirber** [comment]
I don't know why, but I had to set it to `piblic array` so it would not complain.

![Image](https://github.com/user-attachments/assets/383a9b15-983d-498c-8b39-58aae34cf789)

**Comment by develart-projects** [comment]
> I don't know why, but I had to set it to `public array` so it would not complain.
> 
> ![Image](https://github.com/user-attachments/assets/383a9b15-983d-498c-8b39-58aae34cf789)

I'm pretty sure it will work without "array"

**Comment by sirber** [comment]
phpdoc or phpstan likes to have types, but yes

**Comment by sreichel** [comment]
Think you have to use DockBlocks here to make Stan happy :)

**Comment by develart-projects** [comment]
I'll release 1.25.0 soon, dropping 7.1-7.3, adding 8.2.
Anyone to finish the checklist for next 1.26 release pls?
